name: Enforce Checklist

on:
  pull_request:
    types: [opened, edited]

jobs:
  enforce-checklist:
    runs-on: ubuntu-latest
    steps:
      - name: Check for unchecked items in the checklist
        run: |
          if grep -q '\[ \]' "$GITHUB_EVENT_PATH"; then
            echo "Checklist not completed!"
            exit 1
          else
            echo "Checklist completed!"
          fi